### ISSUE TITLE
Unable to create a new app with vs2019 and latest version of catel project template.

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel.Analyzers#11]
I tried to create a project with VS2019 and new version of project template, but it seams something wrong with that template. I couldn't create a project. I get always an error from VS: "one o more errors occurred"
### Steps to reproduce

1. Install the project template for catel wpf application.
2 try to create an app with vs2019.

**Comment by gofrogi** [comment]
i believe it is a wrong place for the issue.

**Comment by GeertvanHorrik** [comment]
Correct, should be Catel.Templates instead.
